django/main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('zkcluster/', include('zkcluster.urls', namespace='zkcluster')),
]

django/main/zkcluster/urls.py
from django.urls import re_path, include
from . import views

app_name = "zk"

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^dashboard/$', views.dashboard, name='dashboard'),

    re_path(r'^terminal/$', views.terminal, name='terminal'),
    re_path(r'^terminal/add$', views.terminal_add, name='terminal_add'),
    re_path(r'^terminal/scan$', views.terminal_scan, name='terminal_scan'),
    re_path(r'^terminal/(?P<action>[\w-]+)/(?P<terminal_id>[0-9]+)/$', views.terminal_action, name='terminal_action'),

    re_path(r'^user/$', views.user, name='user'),
    re_path(r'^user/add/$', views.user_add, name='user_add'),
    re_path(r'^user/(?P<action>[\w-]+)/(?P<user_id>[0-9]+)/$', views.user_action, name='user_action'),

    re_path(r'^attendance/$', views.attendance, name='attendance'),
    re_path(r'^attendance/sync/$', views.attendance_sync, name='attendance_sync'),
]

django/main/zkcluster/models.py
from __future__ import unicode_literals

import zk
from zk.exception import ZKError
from django.utils.translation import ugettext_lazy as _
from django.db import models

from .settings import get_terminal_timeout

class Terminal(models.Model):
    name = models.CharField(_('name'), max_length=200)
    serialnumber = models.CharField(_('serialnumber'), max_length=100, unique=True)
    ip = models.CharField(_('ip'), max_length=15, unique=True)
    port = models.IntegerField(_('port'), default=4370)

    class Meta:
        db_table = 'zk_terminal'

    def __init__(self, *arg, **kwargs):
        self.zkconn = None
        super(Terminal, self).__init__(*arg, **kwargs)

    def __unicode__(self):
        return self.name

    def format(self):
        from signals import PauseSignal
        with PauseSignal(signal=pre_delete, receiver=pre_delete_user, sender=User):
            self.zk_connect()
            self.zk_voice()
            self.zk_clear_data()
            self.users.all().delete()

    def zk_connect(self):
        ip = self.ip
        port = self.port
        terminal = zk.ZK(ip, port, get_terminal_timeout())
        conn = terminal.connect()
        if conn:
            terminal.disable_device()
            self.zkconn = terminal
        else:
            raise ZKError(_('can\'t connect to terminal'))

    def zk_disconnect(self):
        if not self.zkconn:
            raise ZKError(_('terminal connection error'))
        self.zkconn.enable_device()
        self.zkconn.disconnect()

    def zk_restart(self):
        if not self.zkconn:
            raise ZKError(_('terminal connection error'))
        self.zkconn.restart()

    def zk_poweroff(self):
        if not self.zkconn:
            raise ZKError(_('terminal connection error'))
        self.zkconn.poweroff()

    def zk_getserialnumber(self):
        if not self.zkconn:
            raise ZKError(_('terminal connection error'))
        sn = self.zkconn.get_serialnumber()
        return sn

    def zk_voice(self):
        if not self.zkconn:
            raise ZKError(_('terminal connection error'))
        self.zkconn.test_voice()

    def zk_setuser(self, user):
        if not self.zkconn:
            raise ZKError(_('terminal connection error'))

        self.zkconn.set_user(
            uid=int(user.id),
            name=str(user.name),
            privilege=int(user.privilege),
            password=str(user.password),
            user_id=str(user.id)
        )

    def zk_delete_user(self, uid):
        if not self.zkconn:
            raise ZKError(_('terminal connection error'))
        self.zkconn.delete_user(uid)

    def zk_clear_data(self):
        if not self.zkconn:
            raise ZKError(_('terminal connection error'))
        self.zkconn.clear_data()

    def zk_get_attendances(self):
        if not self.zkconn:
            raise ZKError(_('terminal connection error'))
        attendances = self.zkconn.get_attendance()
        return attendances

    def zk_clear_attendances(self):
        if not self.zkconn:
            raise ZKError(_('terminal connection error'))
        self.zkconn.clear_attendance()

class User(models.Model):
    USER_DEFAULT        = 0
    USER_ADMIN          = 14

    PRIVILEGE_COICES = (
        (USER_DEFAULT, _('User')),
        (USER_ADMIN, _('Administrator'))
    )

    name = models.CharField(_('name'), max_length=28)
    privilege = models.SmallIntegerField(_('privilege'), choices=PRIVILEGE_COICES, default=USER_DEFAULT)
    password = models.CharField(_('password'), max_length=8, blank=True, null=True)
    group_id = models.CharField(_('group id'), max_length=7, blank=True, null=True)
    terminal = models.ForeignKey(Terminal, blank=True, null=True, on_delete=models.SET_NULL, related_name='users')

    class Meta:
        db_table = 'zk_user'

    def get_privilege_name(self):
        if self.privilege == self.USER_ADMIN:
            return _('Administrator')

        return _('User')

    def __unicode__(self):
        return self.name

class Attendance(models.Model):
    user = models.ForeignKey(User, related_name='attendances',on_delete=models.CASCADE)
    timestamp = models.DateTimeField()
    status = models.IntegerField()

    class Meta:
        db_table = 'zk_attendance'

    def __unicode__(self):
        return '{}'.format(self.user.name)

# register signal
from .signals import *

django/main/zkcluster/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Terminal, User


class ScanTerminal(forms.Form):
    ip = forms.CharField(
        label=_('IP Address'),
        max_length=15,
        widget=forms.TextInput(attrs={
            'placeholder': '192.168.200.1',
            'class': 'form-control',
        })
    )
    port = forms.IntegerField(
        label=_('Port'),
        widget=forms.TextInput(attrs={
            'value': 4370,
            'class': 'form-control',
        })
    )

    def clean_ip(self):
        ip = self.cleaned_data.get('ip')
        try:
            if self.instance.ip == ip:
                return ip
        except AttributeError:
            pass

        terminal = Terminal.objects.filter(ip__iexact=ip).first()
        if terminal:
            raise forms.ValidationError(_('IP already exists'))
        return ip

class SaveTerminal(forms.ModelForm, ScanTerminal):
    serialnumber = forms.CharField(
        label=_('Serial Number'),
        required=False,
        max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': _('Serial number'),
            'class': 'form-control',
            'readonly': True
        })
    )
    name = forms.CharField(
        label=_('Name'),
        required=False,
        max_length=200,
        widget=forms.TextInput(attrs={
            'placeholder': _('Terminal name'),
            'class': 'form-control',
        })
    )

    def __init__(self, *args, **kwargs):
        super(SaveTerminal, self).__init__(*args, **kwargs)
        self.validate_name = False
        if len(args) > 1:
            self.validate_name = args[1].get('validate_name')

        self.fields['ip'].widget = forms.TextInput(attrs={
            'placeholder': _('IP Address'),
            'class': 'form-control',
            'readonly': True
        })
        self.fields['port'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'readonly': True
        })

    def clean_serialnumber(self):
        serialnumber = self.cleaned_data.get('serialnumber')
        try:
            if self.instance.serialnumber == serialnumber:
                return serialnumber
        except AttributeError:
            pass

        terminal = Terminal.objects.filter(serialnumber__iexact=serialnumber).first()
        if terminal:
            raise forms.ValidationError(_('Serial number already exists'))
        return serialnumber

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if self.validate_name:
            if not name:
                raise forms.ValidationError(_('This field is required.'))
        return name

    class Meta:
        model = Terminal
        fields = ('ip', 'port', 'serialnumber', 'name')

class EditTerminal(SaveTerminal):
    def __init__(self, *args, **kwargs):
        super(EditTerminal, self).__init__(*args, **kwargs)

        self.fields['ip'].widget = forms.TextInput(attrs={
            'placeholder': _('IP Address'),
            'class': 'form-control'
        })
        self.fields['port'].widget = forms.TextInput(attrs={
            'class': 'form-control'
        })

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('name', 'privilege', 'password', 'terminal')
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': _('Full name'),
                'class': 'form-control'
            }),
            'privilege': forms.Select(attrs={
                'class': 'form-control'
            }),
            'password': forms.PasswordInput(attrs={
                'placeholder': _('Password'),
                'class': 'form-control'
            }),
            'terminal': forms.Select(attrs={
                'class': 'form-control'
            })
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['terminal'].required = True

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password and not password.isdigit():
            raise forms.ValidationError(_('Enter a whole number.'))
        return password

django/main/zkcluster/views.py
import zk
from zk.exception import ZKError
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.http import require_http_methods as alowed

from .forms import ScanTerminal, SaveTerminal, EditTerminal, UserForm
from .models import Terminal, User, Attendance

@alowed(['GET'])
@login_required
def index(request):
    return render(request, 'zkcluster/index.html')

@alowed(['GET'])
@login_required
def dashboard(request):
    return render(request, 'zkcluster/dashboard.html')

@alowed(['GET'])
@login_required
def terminal(request):
    terminals = Terminal.objects.all()
    data = {
        'terminals': terminals
    }
    return render(request, 'zkcluster/terminal.html', data)

@alowed(['POST'])
@login_required
def terminal_add(request):
    connected = request.GET.get('connected')
    if connected:
        form = SaveTerminal(request.POST or None, {'validate_name': True})
        if form.is_valid():
            try:
                form.save()
                return redirect('zkcluster:terminal')
            except ZKError:
                messages.add_message(request, messages.ERROR, str(ZKError))
    else:
        form = SaveTerminal(request.POST or None)

    data = {
        'form': form
    }
    return render(request, 'zkcluster/terminal_add.html', data)

@alowed(['GET', 'POST'])
@login_required
def terminal_scan(request):
    form = ScanTerminal(request.POST or None)
    if request.POST and form.is_valid():
        ip = form.cleaned_data['ip']
        port = form.cleaned_data['port']
        terminal = Terminal(
            ip=ip,
            port=port
        )
        # try:
        terminal.zk_connect()
        sn = terminal.zk_getserialnumber()

        # manipulate the POST information
        mutable = request.POST._mutable
        request.POST._mutable = True
        request.POST['serialnumber'] = sn
        request.POST._mutable = mutable

        terminal.zk_disconnect()
        return terminal_add(request)
    # except ZKError:
        messages.add_message(request, messages.ERROR, str(ZKError))

    data = {
        'form': form
    }

    return render(request, 'zkcluster/terminal_scan.html', data)

@alowed(['GET', 'POST'])
@login_required
def terminal_edit(request, terminal_id):
    terminal = get_object_or_404(Terminal, pk=terminal_id)
    form = EditTerminal(request.POST or None, instance=terminal)
    if request.POST and form.is_valid():
        try:
            form.save()
        except ZKError:
            messages.add_message(request, messages.ERROR, str(ZKError))
        return redirect('zkcluster:terminal')
    data = {
        'terminal': terminal,
        'form': form
    }
    return render(request, 'zkcluster/terminal_edit.html', data)

@alowed(['POST'])
def terminal_format(request, terminal_id):
    terminal = get_object_or_404(Terminal, pk=terminal_id)
    try:
        terminal.format()
    except ZKError:
        messages.add_message(request, messages.ERROR, str(ZKError))

    return redirect('zkcluster:terminal')

@alowed(['POST'])
def terminal_delete(request, terminal_id):
    terminal = get_object_or_404(Terminal, pk=terminal_id)
    try:
        terminal.delete()
    except ZKError:
        messages.add_message(request, messages.ERROR, str(ZKError))

    return redirect('zkcluster:terminal')

@alowed(['POST'])
def terminal_restart(request, terminal_id):
    terminal = get_object_or_404(Terminal, pk=terminal_id)
    try:
        terminal.zk_connect()
        terminal.zk_restart()
    except ZKError:
        messages.add_message(request, messages.ERROR, str(ZKError))

    return redirect('zkcluster:terminal')

@alowed(['POST'])
def terminal_poweroff(request, terminal_id):
    terminal = get_object_or_404(Terminal, pk=terminal_id)
    try:
        terminal.zk_connect()
        terminal.zk_poweroff()
        terminal.zk_disconnect()
    except ZKError as e:
        messages.add_message(request, messages.ERROR, str(e))

    return redirect('zkcluster:terminal')

@alowed(['POST'])
def terminal_voice(request, terminal_id):
    terminal = get_object_or_404(Terminal, pk=terminal_id)
    try:
        terminal.zk_connect()
        terminal.zk_voice()
        terminal.zk_disconnect()
    except ZKError as e:
        messages.add_message(request, messages.ERROR, str(e))

    return redirect('zkcluster:terminal')

@alowed(['GET', 'POST'])
@login_required
def terminal_action(request, action, terminal_id):
    if action == 'edit':
        return terminal_edit(request, terminal_id)
    elif action == 'restart':
        return terminal_restart(request, terminal_id)
    elif action == 'poweroff':
        return terminal_poweroff(request, terminal_id)
    elif action == 'voice':
        return terminal_voice(request, terminal_id)
    elif action == 'format':
        return terminal_format(request, terminal_id)
    elif action == 'delete':
        return terminal_delete(request, terminal_id)
    else:
        raise Http404("Action doest not allowed")

@alowed(['GET', 'POST'])
@login_required
def user(request):
    users = User.objects.all()
    data = {
        'users': users
    }
    return render(request, 'zkcluster/user.html', data)

@alowed(['GET', 'POST'])
@login_required
def user_add(request):
    form = UserForm(request.POST or None)
    if request.POST and form.is_valid():
        try:
            form.save()
            return redirect('zkcluster:user')
        except ZKError as e:
            messages.add_message(request, messages.ERROR, str(e))

    data = {
        'form': form
    }
    return render(request, 'zkcluster/user_add.html', data)

@alowed(['GET', 'POST'])
@login_required
def user_edit(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    form = UserForm(request.POST or None, instance=user)
    if request.POST and form.is_valid():
        try:
            form.save()
            return redirect('zkcluster:user')
        except ZKError as e:
            messages.add_message(request, messages.ERROR, str(e))

    data = {
        'form': form
    }
    return render(request, 'zkcluster/user_edit.html', data)

@alowed(['POST'])
@login_required
def delete_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    try:
        user.delete()
    except ZKError as e:
        messages.add_message(request, messages.ERROR, str(e))
    return redirect('zkcluster:user')

@alowed(['GET', 'POST'])
@login_required
def user_action(request, action, user_id):
    if action == 'edit':
        return user_edit(request, user_id)
    elif action == 'delete':
        return delete_user(request, user_id)
    else:
        raise Http404("Action doest not allowed")

@alowed(['GET', 'POST'])
@login_required
def attendance(request):
    attendances = Attendance.objects.all()
    data = {
        'attendances': attendances
    }
    return render(request, 'zkcluster/attendance.html', data)

@alowed(['GET'])
@login_required
def attendance_sync(request):
    terminals = Terminal.objects.all()
    for terminal in terminals:
        try:
            terminal.zk_connect()
            attendances = []
            for attendance in terminal.zk_get_attendances():
                user = User.objects.get(pk=attendance.user_id)
                Attendance.objects.create(
                    user=user,
                    timestamp=attendance.timestamp,
                    status=attendance.status
                )
            terminal.zk_clear_attendances()
            terminal.zk_voice()
            terminal.zk_disconnect()
        except ZKError as e:
            pass
    return redirect('zkcluster:attendance')

django/main/zkcluster/templates/zkcluster/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>zkculster</title>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "zkcluster/bootstrap/css/bootstrap.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "zkcluster/font-awesome/css/font-awesome.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "zkcluster/css/style.css" %}" />
  </head>
  <body>
    <div class="page-wrap">
      <div class="container">
        <nav class="navbar navbar-inverse" role="navigation">
          <div class="container-fluid" id="mainMenu">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toogle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'zkcluster:index' %}">zkcluster</a>
            </div>
            {% if request.user.is_superuser %}
              <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li {% if request.path == '/zkcluster/dashboard/' %}class="active"{% endif %}>
                    <a href="{% url 'zkcluster:dashboard' %}">
                      <i class="fa fa-tachometer" aria-hidden="true"></i> {% trans 'Dashboard' %}
                    </a>
                  </li>
                  <li {% if request.path == '/zkcluster/terminal/' %}class="active"{% endif %}>
                    <a href="{% url 'zkcluster:terminal' %}">
                      <i class="fa fa-wrench" aria-hidden="true"></i> {% trans 'Terminal' %}
                    </a>
                  </li>
                  <li {% if request.path == '/zkcluster/user/' %}class="active"{% endif %}>
                    <a href="{% url 'zkcluster:user' %}">
                      <i class="fa fa-user" aria-hidden="true"></i> {% trans 'User' %}
                    </a>
                  </li>
                  <li {% if request.path == '/zkcluster/attendance/' %}class="active"{% endif %}>
                    <a href="{% url 'zkcluster:attendance' %}">
                      <i class="fa fa-users" aria-hidden="true"></i> {% trans 'Attendance' %}
                    </a>
                  </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li>
                    <form action="{% url 'zkcluster:set_language' %}" method="post" style="padding-top: 15px;">
                      {% csrf_token %}
                      <input name="next" type="hidden" value="{{ redirect_to }}" />
                      <label for="id_lang" style="color: #ffffff;">{% trans 'Language' %}</label>
                      <select name="language" id="id_lang">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                          <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                              {{ language.name_local }}
                          </option>
                        {% endfor %}
                      </select>
                      <input type="submit" class="btn btn-default btn-xs" value={% trans 'Go' %} />
                    </form>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-sign-out" aria-hidden="true"></i> {% trans 'Logout' %}
                    </a>
                  </li>
                </ul>
              </div>
            {% endif %}
          </div>
        </nav>
      </div>
      <div class="container">
        {% for message in messages %}
          <div class="alert alert-{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %}">
            {{ message }}
          </div>
        {% endfor %}
        {% block content %}{% endblock %}
        {% block modal %}{% endblock %}
      </div>
    </div>
    <div class="container">
      <footer class="site-footer">{% trans 'Copyright' %} 2016 &copy; zkcluster</footer>
    </div>
    <!-- js block -->
    <script src="{% static "zkcluster/jquery/jquery-1.12.4.min.js" %}"></script>
    <script src="{% static "zkcluster/bootstrap/js/bootstrap.min.js" %}"></script>
    {% block script %}{% endblock %}
  </body>
</html>

django/main/zkcluster/templates/zkcluster/dashboard.html
{% extends 'zkcluster/base.html' %}
{% load i18n %}

{% block content %}
  <h1>
    {% trans 'Dashboard' %}
  </h1>
{% endblock %}

django/main/zkcluster/templates/zkcluster/index.html
{% extends 'zkcluster/base.html' %}
{% load i18n %}

{% block content %}
  <h1>{% trans 'Welcome' %}</h1>
{% endblock %}

django/main/zkcluster/templates/zkcluster/terminal.html
{% extends 'zkcluster/base.html' %}
{% load i18n %}

{% block content %}
  {% if terminals %}
    <div style="margin-bottom: 10px;">
      <a href="{% url 'zkcluster:terminal_scan' %}">
        <button class="btn btn-default">
          <i class="fa fa-plus-circle" aria-hidden="true"></i> {% trans 'Add Terminal' %}
        </button>
      </a>
    </div>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>{% trans 'ID' %}</th>
          <th>{% trans 'Name' %}</th>
          <th>{% trans 'Serial Number' %}</th>
          <th>{% trans 'IP' %}</th>
          <th>{% trans 'Port' %}</th>
          <th>{% trans 'Action' %}</th>
        </tr>
      </thead>
      <tbody>
        {% for terminal in terminals %}
          <form id="form_restart" method="POST" action="{% url 'zkcluster:terminal_action' 'restart' terminal.id %}">
            {% csrf_token %}
          </form>
          <form id="form_poweroff" method="POST" action="{% url 'zkcluster:terminal_action' 'poweroff' terminal.id %}">
            {% csrf_token %}
          </form>
          <form id="form_voice" method="POST" action="{% url 'zkcluster:terminal_action' 'voice' terminal.id %}">
            {% csrf_token %}
          </form>
          <tr>
            <th scope="row">{{ terminal.id }}</th>
            <td>{{ terminal.name }}</td>
            <td>{{ terminal.serialnumber }}</td>
            <td>{{ terminal.ip }}</td>
            <td>{{ terminal.port }}</td>
            <td style="text-align: center;">
              <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                  {% trans 'Action' %} <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url 'zkcluster:terminal_action' 'edit' terminal.id %}">
                      <i class="fa fa-edit" aria-hidden="true"></i> {% trans 'Edit' %}
                    </a>
                  </li>
                  <li>
                    <a href="#" class="zk_action" id="action_restart">
                      <i class="fa fa-refresh" aria-hidden="true"></i> {% trans 'Restart' %}
                    </a>
                  </li>
                  <li>
                    <a href="#" class="zk_action" id="action_poweroff">
                      <i class="fa fa-power-off" aria-hidden="true"></i> {% trans 'Power Off' %}
                    </a>
                  </li>
                  <li>
                    <a href="#" class="zk_action" id="action_voice">
                      <i class="fa fa-volume-up" aria-hidden="true"></i> {% trans 'Test Sound' %}
                    </a>
                  </li>
                </ul>
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <div class="col-md-12 text-center">
        <p>{% trans 'No terminal found' %}</p>
        <a href="{% url 'zkcluster:terminal_scan' %}">
          <button class="btn btn-default">{% trans 'Add Terminal' %}</button>
        </a>
      </div>
  {% endif %}
{% endblock %}

{% block script %}
  <script>
    $('.zk_action').click(function(){
      var action_id = $(this).attr('id');
      switch(action_id){
        case "action_restart":
          $("#form_restart").submit();
          break;
        case "action_poweroff":
          $("#form_poweroff").submit();
          break;
        case "action_voice":
          $("#form_voice").submit();
          break;
      };
    });
  </script>
{% endblock %}

django/main/zkcluster/templates/zkcluster/terminal_add.html
{% extends 'zkcluster/base.html' %}
{% load i18n %}

{% block content %}
  <div class="row">
    <div class="col-sm-6">
      <form method="POST" action="{% url 'zkcluster:terminal_add' %}?connected=1">
        {% csrf_token %}
        <div class="form-group">
          <label for="{{ form.email.auto_id }}">{{ form.ip.label }}</label>
          <span class="error">{{ form.ip.errors.0 }}</span>
          {{ form.ip }}
        </div>
        <div class="form-group">
          <label for="{{ form.port.auto_id }}">{{ form.port.label }}</label>
          <span class="error">{{ form.port.errors.0 }}</span>
          {{ form.port }}
        </div>
        <div class="form-group">
          <label for="{{ form.serialnumber.auto_id }}">{{ form.serialnumber.label }}</label>
          <span class="error">{{ form.serialnumber.errors.0 }}</span>
          {{ form.serialnumber }}
        </div>
        <div class="form-group">
          <label for="{{ form.name.auto_id }}">{{ form.name.label }}</label>
          <span class="error">{{ form.name.errors.0 }}</span>
          {{ form.name }}
        </div>
        <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
      </form>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    $('#id_name').focus();
  </script>
{% endblock %}

django/main/zkcluster/templates/zkcluster/user.html
{% extends 'zkcluster/base.html' %}
{% load i18n %}

{% block content %}
  {% if users %}
    <div style="margin-bottom: 10px;">
      <a href="{% url 'zkcluster:user_add' %}">
        <button class="btn btn-default">
          <i class="fa fa-plus-circle" aria-hidden="true"></i> {% trans 'Add User' %}
        </button>
      </a>
    </div>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>{% trans 'ID' %}</th>
          <th>{% trans 'Name' %}</th>
          <th>{% trans 'Privilege' %}</th>
          <th>{% trans 'Terminal' %}</th>
          <th>{% trans 'Action' %}</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <th scope="row">{{ user.id }}</th>
            <td>{{ user.name }}</td>
            <td>{{ user.get_privilege_name }}</td>
            <td>{{ user.terminal }}</td>
            <td>
              <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                  {% trans 'Action' %} <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url 'zkcluster:user_action' 'edit' user.id %}">
                      <i class="fa fa-edit" aria-hidden="true"></i> {% trans 'Edit' %}
                    </a>
                  </li>
                </ul>
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <div class="col-md-12 text-center">
        <p>{% trans 'No user found' %}</p>
        <a href="{% url 'zkcluster:user_add' %}">
          <button class="btn btn-default">{% trans 'Add User' %}</button>
        </a>
      </div>
  {% endif %}
{% endblock %}